{
 "title": "Jitsi Meet",
 "description": "Dashboard for stats gathered by 3rd party exporter karrieretutor/jitsi-prom-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(exported_instance)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Conferences",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "conferences{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "participants{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Largest Conference",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "largest_conference{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "RX Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_bytes_received{exported_instance=\"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Conference seconds",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "s",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_conference_seconds{exported_instance=\"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Failed Conferences",
   "type": "singlestat",
   "description": "The total number of failed conferences on the bridge. A conference is marked as failed when all of its channels have failed. A channel is marked as failed if it had no payload activity",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_failed_conferences{exported_instance=\"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "inactive_endpoints",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "inactive_endpoints{exported_instance=\"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance.test.de:9100\",job=~\"hosts\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$instance.test.de:9100\",job=~\"hosts\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$instance.test.de:9100\",job=~\"hosts\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$instance.test.de:9100\",job=~\"hosts\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$instance.test.de:9100\",job=~\"hosts\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance.test.de:9100\",job=~\"hosts\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"} - node_memory_MemFree_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"} - (node_memory_Cached_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"} + node_memory_Buffers_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"} + node_memory_Buffers_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"} - node_memory_SwapFree_bytes{instance=~\"$instance.test.de:9100\",job=~\"hosts\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "threads{exported_instance=\"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Version & Ungefähre Zeit ",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "version{exported_instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "current_timestamp{exported_instance=\"$instance\"}",
     "legendFormat": "{{current_timestamp}}"
    }
   ]
  },
  {
   "title": "Total Channels",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_conferences_created{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "TX Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_bytes_sent{exported_instance=\"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Completed Conferences",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_conferences_completed{exported_instance=\"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Partially Failed Conferences",
   "type": "singlestat",
   "description": "The total number of partially failed conferences on the bridge. A conference is marked as partially failed when some of its channels has failed. A channel is marked as failed if it had no payload activity.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_partially_failed_conferences{exported_instance=\"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "inactive conferences",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "inactive_conferences{exported_instance=\"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Conferences",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "conferences{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "participants{exported_instance=\"$instance\"}",
     "legendFormat": "people"
    }
   ]
  },
  {
   "title": "Video streams",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "videostreams{exported_instance=\"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "total_conferences_created",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_conferences_created{exported_instance=\"$instance\"}",
     "legendFormat": "channels"
    }
   ]
  },
  {
   "title": "endpoints sending audio",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "endpoints_sending_audio{exported_instance=\"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "endpoints sending video",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "endpoints_sending_video{exported_instance=\"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "RTT aggregate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rtt_aggregate{exported_instance=\"$instance\"}",
     "legendFormat": "RTT"
    }
   ]
  },
  {
   "title": "Jitter aggregate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jitter_aggregate{exported_instance=\"$instance\"}",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "Bitrate upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "bit_rate_upload{exported_instance=\"$instance\"}",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Packet rate upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packet_rate_upload{exported_instance=\"$instance\"}",
     "legendFormat": "Packets"
    }
   ]
  },
  {
   "title": "Loss rate upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "loss_rate_upload{exported_instance=\"$instance\"}",
     "legendFormat": "Loss"
    }
   ]
  },
  {
   "title": "Datachannel messages received",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_data_channel_messages_received{exported_instance=\"$instance\"}[5m])",
     "legendFormat": "msg"
    }
   ]
  },
  {
   "title": "Bitrate download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "bit_rate_download{exported_instance=\"$instance\"}",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Packet rate download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packet_rate_download{exported_instance=\"$instance\"}",
     "legendFormat": "Packets"
    }
   ]
  },
  {
   "title": "Loss rate download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "loss_rate_download{exported_instance=\"$instance\"}",
     "legendFormat": "Loss"
    }
   ]
  },
  {
   "title": "Datachannel messages sent",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_data_channel_messages_sent{exported_instance=\"$instance\"}[5m])",
     "legendFormat": "msg"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(total_bytes_sent{exported_instance=\"$instance\"}[1h])",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(total_bytes_received{exported_instance=\"$instance\"}[1h])",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Loss-controlled participant seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(total_loss_controlled_participant_seconds{exported_instance=\"$instance\"}[5m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Loss-degraded participant seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(total_loss_degraded_participant_seconds{exported_instance=\"$instance\"}[5m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Loss-limited participant seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(total_loss_limited_participant_seconds{exported_instance=\"$instance\"}[5m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "p2p_conferences",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p2p_conferences{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "total_packets_received",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_packets_received{exported_instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "total_packets_sent",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_packets_sent{exported_instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "rtp_loss",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rtp_loss{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "total_participants",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_participants{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "receive_only_endpoints",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "receive_only_endpoints{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "total_dominant_speaker_changes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_dominant_speaker_changes{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "num_eps_no_msg_transport_after_delay",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_eps_no_msg_transport_after_delay{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "total_ice_succeeded",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_ice_succeeded{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "total_ice_succeeded_relayed",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_ice_succeeded_relayed{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "total_ice_failed",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_ice_failed{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "total_ice_succeeded_tcp",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_ice_succeeded_tcp{exported_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conference sizes",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum by (le) (conference_sizes{exported_instance=\"$instance\"})",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "conferences_by_video_senders",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum by (le) (conferences_by_video_senders{exported_instance=\"$instance\"})",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "conferences_by_audio_senders",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "sum by (le) (conferences_by_audio_senders{exported_instance=\"$instance\"})",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "other stuff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "graceful_shutdown",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "graceful_shutdown{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "total_colibri_web_socket_messages_sent",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "total_colibri_web_socket_messages_sent{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "graceful_shutdown",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "total_colibri_web_socket_messages_received{exported_instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mucs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "mucs_configured",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mucs_configured{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "muc_clients_configured",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "muc_clients_configured{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "mucs_joined",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mucs_joined{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "muc_clients_connected",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "muc_clients_connected{exported_instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Octo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "total_packets_dropped_octo",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "total_packets_dropped_octo{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "octo_conferences",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "octo_conferences{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "octo_conferences",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "octo_receive_packet_rate{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "octo_endpoints",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "octo_endpoints{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "total_bytes_sent_octo",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "total_bytes_sent_octo{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "octo_receive_bitrate",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "octo_receive_bitrate{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "octo_send_packet_rate",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "octo_send_packet_rate{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "octo_send_bitrate",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "octo_send_bitrate{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "total_bytes_received_octo",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "total_bytes_received_octo{exported_instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "total_packets_received_octo",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "total_packets_received_octo{exported_instance=\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}